### ISSUE TITLE
Many thanks and Farewell

### ISSUE THREAD

**Issue by nyngwang** [antoinemadec/FixCursorHold.nvim#12]
I just saw the updated README.md that the targeted problem (seems to?) has been resolved(eliminated!) on the master branch. Thanks for your help when the (NeoVim) world is under attack(that bug)! Let me keep my star here, for memory :)

**Comment by antoinemadec** [comment]
@nyngwang thank you so much!
However the real MVP's here are neovim's core developer :smiley:

**Comment by jdrouhard** [comment]
This plugin is still useful if we don't want to write swap files as often as we want to trigger CursorHold, though, right? What do you suggest if we still want the decoupling?
