### ISSUE TITLE
Stops Ale command-line updates

### ISSUE THREAD

**Issue by savchenko** [antoinemadec/FixCursorHold.nvim#3]
For some obscure reason, running it with `let g:cursorhold_updatetime = 100` breaks https://github.com/dense-analysis/ale.

Increasing `updateTime` up to 1000ms fixes the problem.

**Comment by antoinemadec** [comment]
@savchenko please feel free to reopen an issue with precise steps to reproduce if this bug persists.

**Comment by savchenko** [comment]
@antoinemadec , thank you for taking care of it. I still don't get the mechanics, but since 23175ef6e66bb6833b5e0a29b3e24a73cfcc7009 `cursorhold_updatetime` set to 500 works fine.
