### ISSUE TITLE
No matching autocommands: gitgutter CursorHold

### ISSUE THREAD

**Issue by Gee19** [antoinemadec/FixCursorHold.nvim#6]
When using this plugin in vim (8.2) with `airblade/vim-gitgutter` I see a message on startup:
`No matching autocommands: gitgutter CursorHold`

Maybe the plugin needs a conditional for the neovim specific logic? Apologies for my ignorance :)

**Comment by antoinemadec** [comment]
Could you please provide me with a **minimal** vimrc so I can reproduce this bug ?

**Comment by Gee19** [comment]
Sure no problem.

```
" vim-plug {{{
call plug#begin('~/.vim/plugged')
" Theme
Plug 'antoinemadec/FixCursorHold.nvim'
Plug 'airblade/vim-gitgutter'
call plug#end()
" }}}
```

Also tried adding the following to no avail
```
set updatetime=100
let g:cursorhold_updatetime = 100
```

**Comment by antoinemadec** [comment]
Will try to take a look at it this weekend!

**Comment by antoinemadec** [comment]
So this is coming from vim-gitgutter:
```vim
  " To keep vim's start-up fast, do not process the buffer when vim is starting.
  " Instead process it a short time later.  Normally we would rely on our
  " CursorHold autocommand to handle this but it turns out CursorHold is not
  " guaranteed to fire if the user has not typed anything yet; so set up a
  " timer instead.  The disadvantage is that if CursorHold does fire, the
  " plugin will do a round of unnecessary work; but since there will not have
  " been any changes to the buffer since the first round, the second round
  " will be cheap.
  if has('vim_starting') && !$VIM_GITGUTTER_TEST
    if exists('*timer_start')
      call timer_start(&updatetime, 'GitGutterCursorHold')
    endif
    return
  endif

" ...

function! GitGutterCursorHold(timer)
  execute 'doautocmd' s:nomodeline 'gitgutter CursorHold'
endfunction
```

Using ```doautocmd ... CursorHold``` conflicts with my plugin.
I use the same kind of tricks in my plugin (timer + doautocmd), there is no way to fix this. Only 1 plugin can mess with this, not 2.

You could however workaround this issue by setting VIM_GITGUTTER_TEST to 1 and adding an VimEnter autocommand:
```vim
  autocmd VimEnter * call gitgutter#process_buffer(bufnr(''), 0)
```

**Comment by Gee19** [comment]
> So this is coming from vim-gitgutter:
> 
> ```viml
>   " To keep vim's start-up fast, do not process the buffer when vim is starting.
>   " Instead process it a short time later.  Normally we would rely on our
>   " CursorHold autocommand to handle this but it turns out CursorHold is not
>   " guaranteed to fire if the user has not typed anything yet; so set up a
>   " timer instead.  The disadvantage is that if CursorHold does fire, the
>   " plugin will do a round of unnecessary work; but since there will not have
>   " been any changes to the buffer since the first round, the second round
>   " will be cheap.
>   if has('vim_starting') && !$VIM_GITGUTTER_TEST
>     if exists('*timer_start')
>       call timer_start(&updatetime, 'GitGutterCursorHold')
>     endif
>     return
>   endif
> 
> " ...
> 
> function! GitGutterCursorHold(timer)
>   execute 'doautocmd' s:nomodeline 'gitgutter CursorHold'
> endfunction
> ```
> 
> Using `doautocmd ... CursorHold` conflicts with my plugin. I use the same kind of tricks in my plugin (timer + doautocmd), there is no way to fix this. Only 1 plugin can mess with this, not 2.
> 
> You could however workaround this issue by setting VIM_GITGUTTER_TEST to 1 and adding an VimEnter autocommand:
> 
> ```viml
>   autocmd VimEnter * call gitgutter#process_buffer(bufnr(''), 0)
> ```

Would setting `VIM_GITGUTTER_TEST=1` globally negatively impact gitgutter in neovim?

I'm testing it either way so feel free to defer, also thank you for looking into this :pray:
