### ISSUE TITLE
Issue when using with fzf.vim and vim-ultest

### ISSUE THREAD

**Issue by Frederick888** [antoinemadec/FixCursorHold.nvim#7]
# Summary

When using with fzf.vim and [vim-ultest](https://github.com/rcarriga/vim-ultest), with `updatetime=300`, fzf commands trigger an error `Error: vim-ultest encountered an unknown error on startup, check v:exception` due to some issue with the `CursorHold` event at https://github.com/rcarriga/vim-ultest/blob/0f4c264129f11950bd471043ce3ab70f3c0545dc/plugin/ultest.vim#L399-L402.

# Steps to reproduce

1. Using the following minimal vimrc, open some file
    ```vim
    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath

    call plug#begin()
    Plug 'antoinemadec/FixCursorHold.nvim'
    Plug 'junegunn/fzf'
    Plug 'junegunn/fzf.vim'
    Plug 'vim-test/vim-test'
    Plug 'rcarriga/vim-ultest', { 'do': ':UpdateRemotePlugins' }
    call plug#end()

    set nocompatible
    set updatetime=300
    set cmdheight=2
    ```
0. `:BLines`

# NeoVim version

```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by antoinemadec** [comment]
@Frederick888 thanks for reporting this issue, it seems to be an issue on ultest's end.
Will open an issue shortly.

**Comment by antoinemadec** [comment]
The issue had nothing to do with FixCursorHold.nvim. It has been fixed, please update vim-ultest and reopen an issue on that repo if the problem persists.
Cheers !
